### PR TITLE
provide instances for Eq,Ord,Show,Read using higher-order typeclasses

### PR DESCRIPTION
**Pull request by andrewthad**
resolves https://github.com/spell-music/data-fix/issues/6

### CODE REVIEW

**Comment by anton-k** [comment]
Why do you remove support for Eq, Ord in base-4.9 and higher?
I guess the intended behaviour is to add support for Eq1, Ord1 etc
if the version of GHC is higher and not to do anything with the code if it's lower.

**Comment by andrewthad** [comment]
I think the diff is a little confusing since github folds it up in the wrong place. Here are [the instance definitions](https://github.com/andrewthad/data-fix/blob/7c476966b35d238f17e7d23a187d0b39af06f164/src/Data/Fix.hs#L72-L98):

```haskell
#if MIN_VERSION_base(4,9,0)
instance Eq1 f => Eq (Fix f) where
    Fix f == Fix g = eq1 f g
instance Ord1 f => Ord (Fix f) where
    compare (Fix f) (Fix g) = compare1 f g
instance Show1 f => Show (Fix f) where
    showsPrec n (Fix f) = showParen (n > 10)
        $ showString "Fix "
        . showsPrec1 11 f
instance Read1 f => Read (Fix f) where
    readsPrec d = readParen (d > 10) $ \r ->
        [(Fix m, t) | ("Fix", s) <- lex r, (m, t) <- readsPrec1 11 s]
#else
instance Show (f (Fix f)) => Show (Fix f) where
    showsPrec n x = showParen (n > 10) $ \s ->
        "Fix " ++ showsPrec 11 (unFix x) s

instance Read (f (Fix f)) => Read (Fix f) where
    readsPrec d = readParen (d > 10) $ \r ->
        [(Fix m, t) | ("Fix", s) <- lex r, (m, t) <- readsPrec 11 s]

instance Eq (f (Fix f)) => Eq (Fix f) where
    (==) = (==) `on` unFix

instance Ord (f (Fix f)) => Ord (Fix f) where
    compare = compare `on` unFix
#endif
```

**Comment by anton-k** [comment]
Ok, I see. Thanks for keeping my lib up to date with Haskell infrastructure!

**Comment by anton-k** [comment]
It's on Hackage!

**Comment by anton-k** [comment]
@andrewthad Sorry, but I have to revert your PR since my music related library that use data-fix for no longer compiles with it. I'm not inclined to write Eq1 and Ord1 instances by hand

And automatic deriving is not working for my case

**Comment by anton-k** [comment]
So this change is not practical for me and it brakes the code that i' using this library for

**Comment by anton-k** [comment]
Oh, my bad it doesn't work without your changes either.. that's really bad

**Comment by anton-k** [comment]
Sorry! So it wasn't the fault of your PR it's something else I need to investigate..
Somehow my libs don't compile anymore on ghc-8.2. There incompatible changes. Ughrm

**Pull request merged**
