### PR TITLE
Instances

### PR DESCRIPTION
**Pull request by xkollar**
* Some work on instances
    * `Show` instance updated so that result of `print` can be fed back to repl.
    * `Read` instance added (`read . show` should be `id`).
* Some sugar on `Eq` and `Ord` instances.
* Some small stuff (HLint, whitespace)

Hope you like it, I am open to feedback, suggestions, and changes.

### CODE REVIEW

**Comment by anton-k** [comment]
Thanks for updates!

**Comment by anton-k** [comment]
I'll upload it on Hackage soon

**Comment by xkollar** [comment]
Thank you `:-)`.

Btw, would you be interested in PRs that would add README and say some sort of CI integration?

**Comment by anton-k** [comment]
that would be great

**Pull request merged**
